name: Build and Deploy 11ty

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build SCSS and 11ty site
        run: npm run build

      - name: Add CNAME
        run: echo 'raredigits.art' > _site/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.RARE_STYLES_PAT }}
          publish_dir: ./_site
          publish_branch: gh-pages
          disable_nojekyll: true